# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#/Users/tobiasboogh/Projects/Private/XcovTest/fastlane/xcov_report/xccovreport-0.xccovreport
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do
    scan(
        project: "XcovTest.xcodeproj",
        code_coverage: true
    )
    git_branch = ENV['BITRISE_GIT_BRANCH']
    git_branch_destination = ENV['BITRISEIO_GIT_BRANCH_DEST']
    pull_request_id = ENV['BITRISE_PULL_REQUEST']
    repo_url = ENV['BITRISEIO_PULL_REQUEST_REPOSITORY_URL']
    xcov(
        project: "XcovTest.xcodeproj",
        coveralls_repo_token: ENV["REPOKEY"],
        coveralls_service_build_url: repo_url,
        coveralls_service_number: ENV['BITRISE_BUILD_NUMBER'],
        coveralls_service_branch: git_branch_destination,
        coveralls_service_pull_request: pull_request_id,
        xccov_file_direct_path: ENV["SCAN_GENERATED_XCRESULT_PATH"]
    )
  end
end
