name: iOS starter workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.1'
      - name: Fastlane Action
        # You may pin to the exact commit or the version.
        # uses: maierj/fastlane-action@a17717b67f153f900ec39b12da587067911b8c56
        uses: maierj/fastlane-action@v2.2.0
        env:
          TESTKEY: ${{ secrets.TESTKEY }}
        with:
          # The lane that should be executed.
          lane: test
          # The relative path from the project root directory to the subdirectory where the fastlane folder is located.
#           subdirectory: # optional
          # The directory where Ruby gems should be installed to and cached. If a relative path is specified, it's applied relative to the location of the Gemfile, which is either the project root or the directory from the `subdirectory` parameter.
#           bundle-install-path: # optional
          # If set to true, adds the verbose option to the fastlane command for extended log output.
          verbose: true
          # The action tracks usage in Firebase by default. You can disable tracking by setting this parameter to 'true'.
#           skip-tracking: # optional
          # The options that should be passed as arguments to the lane. The options should be serialized as a JSON object.
#           options: # optional
          # The env value that should be passed as an argument to the lane. The value should match to one of your fastlane env files.
#           env: # optional
